
CREATE TABLE exoplanets(
       loc_rowid serial PRIMARY KEY,
       pl_hostname VARCHAR (255),
       pl_name  VARCHAR (255),
       pl_discmethod VARCHAR (255),
       pl_pnum INT,
       pl_orbper NUMERIC,
       pl_orbpererr1 NUMERIC,
       pl_orbpererr2  NUMERIC,
       pl_orbperlim  NUMERIC,
       pl_bmassj NUMERIC,
       pl_radj  NUMERIC,
       pl_dens	 NUMERIC,
       gaia_dist  NUMERIC,
       st_teff  NUMERIC,
       st_mass NUMERIC,
       st_rad NUMERIC,
       pl_eqt NUMERIC,
       pl_massj NUMERIC,
       pl_masse NUMERIC,
       pl_rade NUMERIC,
       pl_rads NUMERIC,
       pl_ratdor NUMERIC,
       pl_disc	VARCHAR (255),
       pl_disc_reflink VARCHAR (255),
       pl_facility VARCHAR (255),
       pl_telescope VARCHAR (255),
       pl_instrument VARCHAR (255),
       pl_mnum INT,
       pl_pelink VARCHAR (255),
       pl_edelink VARCHAR (255),
       st_sp NUMERIC,
       st_logg NUMERIC,
       st_lum NUMERIC,
       st_metfe NUMERIC,
       st_metratio VARCHAR (255),
       st_age NUMERIC
);
